import PDFDocument from "pdfkit";
import XLSX from "xlsx";

/**
 * Generates a professional CSV string from an array of flat objects
 * @param {Array<Object>} data - Flat data array
 * @returns {String} CSV string
 */
export const generateCSV = (data) => {
  if (!data || data.length === 0) return "";

  const headers = Object.keys(data[0]);
  const csvRows = [];

  csvRows.push(headers.join(","));

  for (const row of data) {
    const values = headers.map((header) => {
      const val = row[header] === undefined || row[header] === null ? "" : row[header];
      const escaped = ("" + val).replace(/"/g, '\\"');
      return `"${escaped}"`;
    });
    csvRows.push(values.join(","));
  }

  return csvRows.join("\n");
};

/**
 * Generates an Excel XLSX workbook Buffer from data
 */
export const generateExcel = (data, sheetName = "Export") => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  return XLSX.write(workbook, { type: "buffer", bookType: "xlsx" });
};

/**
 * Markdown export for Intelligence Hub reports (dynamic).
 */
export const generateMarkdown = (report) => {
  const type = report.type || report.reportType || "report";
  const lines = [
    `# ${report.title || "Untitled Report"}`,
    "",
    `**Type:** ${type}  `,
    `**Source:** ${report.source || "n/a"}  `,
    `**Created:** ${report.createdAt ? new Date(report.createdAt).toISOString() : "n/a"}  `,
    report.confidence != null ? `**Confidence:** ${report.confidence}%  ` : null,
    report.summary ? "" : null,
    report.summary ? "## Summary" : null,
    report.summary ? "" : null,
    report.summary || null,
    "",
    "## Content",
    "",
    "```json",
    typeof report.content === "string"
      ? report.content
      : JSON.stringify(report.content ?? {}, null, 2),
    "```",
  ];

  if (report.metadata && Object.keys(report.metadata).length) {
    lines.push("", "## Metadata", "", "```json", JSON.stringify(report.metadata, null, 2), "```");
  }

  if (Array.isArray(report.tags) && report.tags.length) {
    lines.push("", `**Tags:** ${report.tags.join(", ")}`);
  }

  lines.push("", "---", "_Generated by Social IQ Intelligence Hub_");
  return lines.filter((l) => l !== null).join("\n");
};

/**
 * JSON export (pretty) for hub reports.
 */
export const generateJSON = (report) => {
  const payload = {
    id: report._id || report.id,
    title: report.title,
    type: report.type,
    source: report.source,
    summary: report.summary,
    description: report.description,
    confidence: report.confidence,
    tags: report.tags,
    category: report.category,
    sourceModules: report.sourceModules,
    content: report.content,
    dossier: report.dossier || null,
    metadata: report.metadata,
    createdAt: report.createdAt,
    updatedAt: report.updatedAt,
    version: report.version,
    reportVersion: report.reportVersion,
    analysisVersion: report.analysisVersion,
    engineVersion: report.engineVersion,
  };
  return JSON.stringify(payload, null, 2);
};

/**
 * Generates a professional PDF report and writes to a stream/buffer callback
 */
export const generatePDF = (reportData, callback) => {
  const doc = new PDFDocument({ margin: 50, size: "A4" });
  const chunks = [];

  doc.on("data", (chunk) => chunks.push(chunk));
  doc.on("end", () => callback(Buffer.concat(chunks)));

  doc.fillColor("#111319").rect(0, 0, 595.28, 120).fill();

  doc.fillColor("#6366f1").fontSize(26).font("Helvetica-Bold").text("SOCIAL IQ", 50, 40);
  doc.fillColor("#94a3b8").fontSize(10).font("Helvetica").text("Enterprise Performance Analytics Engine", 50, 70);

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.fillColor("#ffffff").fontSize(10).text(`Generated: ${dateStr}`, 450, 70, { align: "right" });

  doc.fillColor("#0f172a").fontSize(18).font("Helvetica-Bold").text(reportData.title || "Analytics Report", 50, 150);
  doc.fontSize(10).font("Helvetica-Oblique").text(reportData.subtitle || "", 50, 175);
  doc.moveDown(1.5);

  if (reportData.summary) {
    doc.fillColor("#1e293b").fontSize(11).font("Helvetica-Bold").text("Overview & Highlights", 50, doc.y);
    doc.moveDown(0.4);
    doc.fillColor("#334155").fontSize(10).font("Helvetica").text(reportData.summary, { width: 500, align: "justify" });
    doc.moveDown(2);
  }

  if (reportData.kpis && reportData.kpis.length > 0) {
    doc.fillColor("#1e293b").fontSize(11).font("Helvetica-Bold").text("Core Performance Indicators", 50, doc.y);
    doc.moveDown(0.6);

    const startY = doc.y;
    let currentX = 50;

    reportData.kpis.forEach((kpi) => {
      doc.fillColor("#f8fafc").rect(currentX, startY, 110, 60).fill();
      doc.strokeColor("#e2e8f0").lineWidth(1).rect(currentX, startY, 110, 60).stroke();

      doc.fillColor("#64748b").fontSize(8).font("Helvetica-Bold").text(kpi.label.toUpperCase(), currentX + 8, startY + 12, { width: 94 });
      doc.fillColor("#4f46e5").fontSize(14).font("Helvetica-Bold").text("" + kpi.value, currentX + 8, startY + 28, { width: 94 });

      currentX += 120;
    });

    doc.y = startY + 80;
    doc.moveDown(1);
  }

  if (reportData.table && reportData.table.rows) {
    doc.fillColor("#1e293b").fontSize(11).font("Helvetica-Bold").text(reportData.table.title || "Data Table", 50, doc.y);
    doc.moveDown(0.6);

    const colWidths = reportData.table.colWidths || [];
    let x = 50;
    (reportData.table.columns || []).forEach((col, i) => {
      doc.fillColor("#64748b").fontSize(8).font("Helvetica-Bold").text(col, x, doc.y, { width: colWidths[i] || 100 });
      x += colWidths[i] || 100;
    });
    doc.moveDown(0.8);

    reportData.table.rows.forEach((row) => {
      let rx = 50;
      const y = doc.y;
      row.forEach((cell, i) => {
        doc.fillColor("#334155").fontSize(8).font("Helvetica").text(String(cell ?? ""), rx, y, {
          width: colWidths[i] || 100,
        });
        rx += colWidths[i] || 100;
      });
      doc.moveDown(0.7);
      if (doc.y > 740) doc.addPage();
    });
  }

  if (reportData.notes) {
    doc.moveDown(1);
    doc.fillColor("#1e293b").fontSize(11).font("Helvetica-Bold").text("Notes / Detail", 50, doc.y);
    doc.moveDown(0.4);
    doc.fillColor("#334155").fontSize(9).font("Helvetica").text(String(reportData.notes).slice(0, 8000), {
      width: 500,
    });
  }

  doc.end();
};
