/**
 * Professional Markdown Political Intelligence Report from assembled dossier.
 */
export function generateDossierMarkdown(dossier) {
  const s = dossier?.sections || {};
  const lines = [];
  let sectionNum = 0;
  const next = (title) => {
    sectionNum += 1;
    lines.push(`## ${sectionNum}. ${title}`);
    lines.push("");
  };

  const cover = s.cover || {};
  const headline = cover.politicianName || cover.title || "Intelligence Report";

  lines.push(`# ${cover.brand || "Social IQ"}`);
  lines.push("");
  lines.push(`## ${headline}`);
  lines.push("");
  lines.push(`**${cover.documentType || "Political Intelligence Report"}**`);
  lines.push("");
  if (cover.reportTypeLabel) lines.push(`*${cover.reportTypeLabel}*  `);
  if (cover.currentPosition) lines.push(`**Position:** ${cover.currentPosition}  `);
  if (cover.party) lines.push(`**Party:** ${cover.party}  `);
  if (cover.state) lines.push(`**State:** ${cover.state}  `);
  if (cover.confidence != null) lines.push(`**Confidence:** ${cover.confidence}%  `);
  if (cover.generatedAt) lines.push(`**Generated:** ${new Date(cover.generatedAt).toISOString().slice(0, 10)}  `);
  if (cover.reportVersion) lines.push(`**Report Version:** ${cover.reportVersion}  `);
  if (cover.generatedBy) lines.push(`**Generated By:** ${cover.generatedBy}  `);
  lines.push("");
  lines.push("---");
  lines.push("");

  if (s.executiveSummary?.paragraphs?.length) {
    next(s.executiveSummary.label || "Summary");
    for (const p of s.executiveSummary.paragraphs) {
      lines.push(p);
      lines.push("");
    }
  }

  if (s.politicalProfile) {
    next("Political Profile");
    lines.push("| Field | Value |");
    lines.push("| --- | --- |");
    for (const f of s.politicalProfile.fields || []) {
      lines.push(`| ${f.label} | ${String(f.value).replace(/\|/g, "/")} |`);
    }
    if (s.politicalProfile.profileConfidence != null) {
      lines.push(`| Profile Confidence | ${s.politicalProfile.profileConfidence}% |`);
    }
    lines.push("");
    if (s.politicalProfile.socialAccounts?.length) {
      lines.push("### Social Accounts");
      lines.push("");
      for (const a of s.politicalProfile.socialAccounts) {
        lines.push(`- **${a.platform}:** ${a.url}`);
      }
      lines.push("");
    }
  }

  if (s.careerTimeline?.events?.length) {
    next("Career Timeline");
    for (const e of s.careerTimeline.events) {
      const title = String(e.title || "").trim();
      let description = String(e.description || "").trim();
      if (
        description &&
        (description.toLowerCase() === title.toLowerCase() ||
          title.toLowerCase().includes(description.toLowerCase()))
      ) {
        description = "";
      }
      lines.push(`### ${e.year || "Event"}`);
      lines.push("");
      lines.push(`**${title}**`);
      if (description) {
        lines.push("");
        lines.push(description);
      }
      lines.push("");
    }
  }

  if (s.electionHistory?.rows?.length) {
    next("Election History");
    lines.push("| Election | Constituency | Party | Result | Votes | Vote % | Margin | Opponent | Source |");
    lines.push("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
    for (const r of s.electionHistory.rows) {
      lines.push(
        `| ${r.election || ""} | ${r.constituency || ""} | ${r.party || ""} | ${r.result || ""} | ${r.votes ?? ""} | ${r.votePct ?? ""} | ${r.margin ?? ""} | ${r.opponent || ""} | ${r.source || ""} |`
      );
    }
    lines.push("");
  }

  if (s.influenceIntelligence) {
    next("Influence Intelligence");
    lines.push("| Metric | Score |");
    lines.push("| --- | --- |");
    for (const m of s.influenceIntelligence.metrics || []) {
      lines.push(`| ${m.label} | ${m.value} |`);
    }
    lines.push("");
    if (s.influenceIntelligence.explanation) {
      lines.push(s.influenceIntelligence.explanation);
      lines.push("");
    }
  }

  if (s.geographicInfluence) {
    next("Geographic Influence");
    if (s.geographicInfluence.primaryRegion) {
      lines.push(`**Primary Region:** ${s.geographicInfluence.primaryRegion}  `);
    }
    if (s.geographicInfluence.secondaryRegions?.length) {
      lines.push(`**Secondary Regions:** ${s.geographicInfluence.secondaryRegions.join(", ")}  `);
    }
    if (s.geographicInfluence.emergingRegions?.length) {
      lines.push(`**Emerging Regions:** ${s.geographicInfluence.emergingRegions.join(", ")}  `);
    }
    if (s.geographicInfluence.verifiedCoverage != null) {
      lines.push(`**Verified Coverage:** ${s.geographicInfluence.verifiedCoverage}  `);
    }
    lines.push("");

    const tiers = s.geographicInfluence.influenceTiers?.length
      ? s.geographicInfluence.influenceTiers
      : (s.geographicInfluence.states || [])
          .filter((g) => g.tier)
          .map((g) => ({ state: g.state, tier: g.tier, influence: g.influence }));

    if (tiers.length) {
      lines.push("| State | Influence Tier | Influence |");
      lines.push("| --- | --- | --- |");
      for (const g of tiers) {
        lines.push(`| ${g.state || ""} | ${g.tier || ""} | ${g.influence ?? ""} |`);
      }
      lines.push("");
    }
  }

  if (s.newsSentiment) {
    next("News & Sentiment");
    for (const n of s.newsSentiment.items || []) {
      if (n.url) {
        lines.push(`### [${n.headline}](${n.url})`);
      } else {
        lines.push(`### ${n.headline}`);
        lines.push("");
        lines.push("*Verified article unavailable*");
      }
      const meta = [n.source, n.date || n.publishedAt, n.sentiment].filter(Boolean).join(" · ");
      if (meta) lines.push(`*${meta}*`);
      if (n.summary) lines.push(n.summary);
      lines.push("");
    }
  }

  if (s.aiInsights?.blocks?.length) {
    next("AI Insights");
    for (const b of s.aiInsights.blocks) {
      lines.push(`### ${b.title || "Insight"}`);
      if (b.body) lines.push(b.body);
      if (Array.isArray(b.items)) {
        for (const item of b.items) lines.push(`- ${item}`);
      }
      lines.push("");
    }
  }

  if (s.evidenceSources?.items?.length || s.evidenceSources?.groups) {
    next("Evidence & Sources");
    const items = Array.isArray(s.evidenceSources.items)
      ? s.evidenceSources.items
      : Object.values(s.evidenceSources.groups || {}).flat();
    for (const item of items) {
      const bits = [
        item.description,
        item.confidenceLabel,
        item.lastUpdated
          ? `Updated: ${new Date(item.lastUpdated).toISOString().slice(0, 10)}`
          : null,
      ].filter(Boolean);
      lines.push(`- **${item.name}**`);
      if (bits.length) lines.push(`  ${bits.join(" · ")}`);
      lines.push("");
    }
  }

  if (s.metadata) {
    next("Metadata");
    lines.push("| Field | Value |");
    lines.push("| --- | --- |");
    const m = s.metadata;
    const rows = [
      ["Generated", m.generated],
      ["Updated", m.updated],
      ["Engine Version", m.engineVersion],
      ["Analysis Version", m.analysisVersion],
      ["Report Version", m.reportVersion],
      ["Template Version", m.templateVersion],
      ["Confidence", m.confidence],
      ["Modules Included", Array.isArray(m.modulesIncluded) ? m.modulesIncluded.join(", ") : ""],
      ["Generated By", m.generatedBy],
    ];
    for (const [label, value] of rows) {
      lines.push(`| ${label} | ${value ?? "—"} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Confidential — Generated by Social IQ Intelligence Hub*");
  return lines.join("\n");
}
